sudo: required 
services:
  - docker

before_install:
  - docker build -t rahulraut/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rahulraut/react-test npm test

after_success:
  - docker build -t rahulraut/multi-client ./client
  - docker build -t rahulraut/multi-nginx ./nginx
  - docker build -t rahulraut/multi-worker ./worker
  - docker build -t rahulraut/multi-server ./server
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take above images push it to docker repository 
  - docker push rahulraut/multi-client
  - docker push rahulraut/multi-nginx
  - docker push rahulraut/multi-worker
  - docker push rahulraut/multi-server


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-936732622526
  bucket_path: docker_multi
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY